-- ============================================================
-- 015 — client_ref idempotency key for offline Yanbu'a/Quran replay
--
-- Extends the app-layer offline write queue (ADR-029) from
-- attendance/murajaah to Yanbu'a and Quran recitation recording. Those
-- two writes are plain inserts into `yanbua_progress`/`quran_progress`
-- with no unique constraint at all, unlike attendance (upsert on
-- `(session_id, student_id)`) and murajaah_log (`unique (assignment_id,
-- date)`). Without one, a request that actually reaches the server and
-- commits, but whose response is lost before the client sees it (the
-- device drops offline at that exact moment, or the tab closes), would
-- be queued and replayed as a brand-new insert — a silent duplicate
-- progress row, since nothing on either table would reject it.
--
-- `client_ref` is a client-generated uuid (the offline queue entry's own
-- `id`, already generated by `crypto.randomUUID()` in
-- `offlineQueue.ts`), unique per table, nullable so an ordinary online
-- insert — which never sets it — is unaffected: Postgres unique indexes
-- allow unlimited NULLs. A replay that lands after its insert already
-- succeeded hits this constraint's `23505` and is treated as
-- already-delivered rather than an error, the same reasoning
-- `offlineReplay.ts` already applies to a murajaah replay hitting
-- `murajaah_log`'s `unique (assignment_id, date)`.
--
-- No RLS policy change: `yanbua_tutor_insert`/`quran_tutor_insert`
-- (013_student_assistant_self_write.sql) check only `student_id` and
-- `tutor_id`, which is unaffected by an additional nullable column — RLS
-- is row-scoped, not column-scoped.
--
-- No data migration: existing rows get `client_ref = null`, which the
-- unique index permits without limit.
-- ============================================================

alter table public.yanbua_progress
  add column client_ref uuid unique;

alter table public.quran_progress
  add column client_ref uuid unique;
